name: Scrape ABC Jogger 28" inventory

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,16,26,36,46,56 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo for script to access
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://shop.lululemon.com/api/p/mens-trousers/ABC-Pant-Slim-30/_/prod9610173\?color\=32476\&sz\=30 | jq '.data.attributes."purchase-attributes"."size-driver"[] | select(.size | contains("30"))' > abc_slim_pant_inventory.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push